# TCL File Generated by Component Editor 23.1
# Sun Mar 30 23:38:52 HKT 2025
# DO NOT MODIFY


# 
# avmm_sdram_read_wrapper "Avalon MM SDRAM Read Wrapper" v1.0
# jyseric 2025.03.30.23:38:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avmm_sdram_read_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME avmm_sdram_read_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR jyseric
set_module_property DISPLAY_NAME "Avalon MM SDRAM Read Wrapper"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avmm_sdram_read_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avmm_sdram_read_wrapper.sv SYSTEM_VERILOG PATH ../design_rtl/io/avmm_sdram_read_wrapper.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SDRAM_DATA_W INTEGER 128 ""
set_parameter_property SDRAM_DATA_W DEFAULT_VALUE 128
set_parameter_property SDRAM_DATA_W DISPLAY_NAME SDRAM_DATA_W
set_parameter_property SDRAM_DATA_W WIDTH ""
set_parameter_property SDRAM_DATA_W TYPE INTEGER
set_parameter_property SDRAM_DATA_W UNITS None
set_parameter_property SDRAM_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SDRAM_DATA_W DESCRIPTION ""
set_parameter_property SDRAM_DATA_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 readdata readdata Input "((SDRAM_DATA_W-1)) - (0) + 1"
add_interface_port m0 readdatavalid readdatavalid Input 1
add_interface_port m0 waitrequest waitrequest Input 1
add_interface_port m0 read read Output 1
add_interface_port m0 address address Output 32
add_interface_port m0 burstcount burstcount Output 11


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point read
# 
add_interface read conduit end
set_interface_property read associatedClock clock
set_interface_property read associatedReset reset
set_interface_property read ENABLED true
set_interface_property read EXPORT_OF ""
set_interface_property read PORT_NAME_MAP ""
set_interface_property read CMSIS_SVD_VARIABLES ""
set_interface_property read SVD_ADDRESS_GROUP ""

add_interface_port read read_start read_start Input 1
add_interface_port read read_cnt read_cnt Input 11
add_interface_port read read_data read_data Output "((SDRAM_DATA_W-1)) - (0) + 1"
add_interface_port read read_addr read_addr Input 32
add_interface_port read read_done read_done Output 1
add_interface_port read read_valid read_valid Output 1

